# fly.toml app configuration file generated for discord-telegram-simple-relay on 2023-10-07T21:12:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-telegram-simple-relay"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
